# Generated by Django 5.2 on 2025-05-26 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('order_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationSheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calc_row_type', models.CharField(choices=[(None, ''), ('Доход', 'Доход'), ('Расход', 'Расход')], max_length=100)),
                ('calc_row_contragent', models.CharField(max_length=500)),
                ('calc_row_service_name', models.CharField(max_length=200)),
                ('calc_row_currency', models.CharField(choices=[(None, ''), ('RUB', 'RUB'), ('CNY', 'CNY'), ('USD', 'USD'), ('EUR', 'EUR'), ('KZT', 'KZT')], max_length=3)),
                ('calc_row_count', models.PositiveIntegerField()),
                ('calc_row_single_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calc_row_has_nds', models.CharField(choices=[(None, ''), ('Y', 'Y'), ('N', 'N')], max_length=1)),
                ('calc_row_ttl_nds_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calc_row_ttl_price_without_nds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calculation_sheet.calculationsheet')),
            ],
        ),
    ]
