# Generated by Django 5.2 on 2025-05-26 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationsheet',
            name='calc_row_currency',
            field=models.CharField(choices=[(None, ''), ('RUB', 'RUB'), ('CNY', 'CNY'), ('USD', 'USD'), ('EUR', 'EUR'), ('KZT', 'KZT')], max_length=3),
        ),
        migrations.AlterField(
            model_name='calculationsheet',
            name='calc_row_has_nds',
            field=models.CharField(choices=[(None, ''), ('Y', 'Y'), ('N', 'N')], max_length=1),
        ),
        migrations.AlterField(
            model_name='calculationsheet',
            name='calc_row_type',
            field=models.CharField(choices=[(None, ''), ('Доход', 'Доход'), ('Расход', 'Расход')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calculationsheet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 8, 13, 16, 965940, tzinfo=datetime.timezone.utc)),
        ),
    ]
