# Generated by Django 5.2 on 2025-05-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationsheet',
            options={'verbose_name': 'Расчетный лист', 'verbose_name_plural': 'Расчетный лист'},
        ),
        migrations.AlterModelOptions(
            name='calculationsheetrow',
            options={'verbose_name': 'Доход/Расход', 'verbose_name_plural': 'Доход/Расход'},
        ),
        migrations.AddField(
            model_name='calculationsheet',
            name='calc_sheet_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calculationsheet',
            name='order_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
