# Generated by Django 5.2 on 2025-05-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0002_alter_calculationsheet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheetrow',
            name='calc_row_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
