# Generated by Django 5.2 on 2025-06-04 07:49

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0003_calculationsheetrow_calc_row_exchange_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationsheetrow',
            old_name='author',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='calculationsheetrow',
            name='edited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calculationsheetrow',
            name='edited_by',
            field=models.CharField(default=datetime.datetime(2025, 6, 4, 10, 49, 53, 381756), max_length=100),
            preserve_default=False,
        ),
    ]
