# Generated by Django 5.2 on 2025-06-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0004_rename_author_calculationsheetrow_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheet',
            name='sbis_href',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
