# Generated by Django 5.2 on 2025-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0005_calculationsheet_sbis_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheet',
            name='sbis_approval_status',
            field=models.CharField(default='Не отправлено на согласование', max_length=128),
        ),
    ]
