# Generated by Django 5.2 on 2025-06-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0006_calculationsheet_sbis_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationsheet',
            name='sbis_approval_status',
            field=models.CharField(default='нет задачи в Сбис на согласование', max_length=128),
        ),
    ]
