# Generated by Django 5.2 on 2025-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0007_alter_calculationsheet_sbis_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheet',
            name='sbis_doc_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
