# Generated by Django 5.2 on 2025-07-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0008_calculationsheet_sbis_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheetrow',
            name='calc_row_measure',
            field=models.CharField(choices=[(None, ''), ('декларация', 'декларация'), ('контейнер', 'контейнер'), ('KGS', 'KGS'), ('TEU', 'TEU'), ('Тонна', 'Тонна'), ('SETS', 'SETS'), ('CBM', 'CBM'), ('托', '托'), ('MT', 'MT'), ('车', '车'), ('台', '台'), ('DAY', 'DAY'), ('railway carriage', 'railway carriage'), ('45HC', '45HC'), ('20 NEW VAN', '20 NEW VAN'), ('40GP', '40GP'), ('45RH', '45RH'), ('40TR', '40TR'), ('20GP', '20GP'), ('20TK', '20TK'), ('40HC', '40HC'), ('40RH', '40RH'), ('40HCRF', '40HCRF'), ('40HC NEW VAN', '40HC NEW VAN'), ('40HCPW', '40HCPW'), ('40OT', '40OT'), ('40RF', '40RF'), ('20OT', '20OT'), ('20HC', '20HC'), ('20FR', '20FR'), ('40FR', '40FR'), ('40TK', '40TK')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculationsheetrow',
            name='calc_row_settlement_procedure',
            field=models.CharField(choices=[(None, ''), ('PP', 'PP'), ('CC', 'CC'), ('PC', 'PC'), ('CP', 'CP')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
