# Generated by Django 5.2 on 2025-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0009_calculationsheetrow_calc_row_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationsheet',
            name='order_no',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
