# Generated by Django 5.2 on 2025-08-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0010_alter_calculationsheet_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationsheetrow',
            name='calc_row_has_nds',
        ),
        migrations.RemoveField(
            model_name='calculationsheetrow',
            name='calc_row_ttl_nds_price',
        ),
        migrations.RemoveField(
            model_name='calculationsheetrow',
            name='calc_row_ttl_price_without_nds',
        ),
    ]
