# Generated by Django 5.2 on 2025-09-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0011_remove_calculationsheetrow_calc_row_has_nds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheet',
            name='uploaded_at_sol',
            field=models.CharField(default='Нет', max_length=32),
        ),
        migrations.AlterField(
            model_name='calculationsheet',
            name='sbis_approval_status',
            field=models.CharField(default='Нет задачи в Сбис на согласование', max_length=128),
        ),
    ]
