# Generated by Django 5.2 on 2025-09-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0012_calculationsheet_uploaded_at_sol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationsheet',
            name='calc_sheet_no',
        ),
    ]
