# Generated by Django 5.2 on 2025-10-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0013_remove_calculationsheet_calc_sheet_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheetrow',
            name='calc_row_departure_station',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculationsheetrow',
            name='calc_row_destination_station',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculationsheetrow',
            name='calc_row_original_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
