# Generated by Django 5.2 on 2025-10-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0014_calculationsheetrow_calc_row_departure_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheetrow',
            name='calc_row_delete_from_sol',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculationsheetrow',
            name='calc_row_original_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
