# Generated by Django 5.2 on 2025-10-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0015_calculationsheetrow_calc_row_delete_from_sol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheetrow',
            name='calc_row_need_update_in_sol',
            field=models.SmallIntegerField(default=0),
        ),
    ]
