# Generated by Django 5.2 on 2025-10-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0016_calculationsheetrow_calc_row_need_update_in_sol'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheet',
            name='calc_sheet_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='calculationsheet',
            name='order_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
