# Generated by Django 5.2 on 2025-10-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0017_calculationsheet_calc_sheet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsheetrow',
            name='calc_row_is_fixed_as_planned',
            field=models.SmallIntegerField(default=0),
        ),
    ]
