# Generated by Django 5.2 on 2025-10-29 07:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0018_calculationsheetrow_calc_row_is_fixed_as_planned'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationSheetPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_by', models.CharField(max_length=100)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('planned_calc_sheet_pdf_bytes', models.TextField(blank=True, null=True)),
                ('planned_calc_sheet_pdf_is_uploaded', models.SmallIntegerField(default=0)),
                ('actual_calc_sheet_pdf_bytes', models.TextField(blank=True, null=True)),
                ('actual_calc_sheet_pdf_is_uploaded', models.SmallIntegerField(default=0)),
                ('calculation_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calculation_sheet.calculationsheet')),
            ],
            options={
                'verbose_name': 'ПДФ по р\\л',
                'verbose_name_plural': 'ПДФ по р\\л',
            },
        ),
    ]
