# Generated by Django 5.2 on 2025-10-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_sheet', '0019_calculationsheetpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationsheetpdf',
            old_name='actual_calc_sheet_pdf_bytes',
            new_name='actual_calc_sheet_pdf_base64',
        ),
        migrations.RenameField(
            model_name='calculationsheetpdf',
            old_name='planned_calc_sheet_pdf_bytes',
            new_name='planned_calc_sheet_pdf_base64',
        ),
    ]
